DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS ratings;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(

id SERIAL PRIMARY KEY,
firstname VARCHAR(60) NOT NULL,
surname VARCHAR(60) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(100) NOT NULL

);

CREATE TABLE IF NOT EXISTS ratings(

id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
movie_id VARCHAR(60) NOT NULL,
rating VARCHAR(60) NOT NULL,
CONSTRAINT fk_users
FOREIGN KEY(user_id)
REFERENCES users(id)


);
CREATE TABLE IF NOT EXISTS ratings_avg(
    id SERIAL PRIMARY KEY,
    movie_id VARCHAR(60) NOT NULL,
    ave_ratings VARCHAR(60)
);



